Customizing shell for Lassen.

The following have been reloaded with a version change:
  1) base-gcc/8.3.1 => base-gcc/11.2.1


Lmod is automatically replacing "clang/ibm-16.0.6-cuda-11.2.0-gcc-8.3.1" with
"gcc/10.2.1".


Due to MODULEPATH changes, the following have been reloaded:
  1) spectrum-mpi/rolling-release

Activating 'timing.pilot' environment for '/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/bin/conda'.
/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/scalability_test
/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/scalability_test
Driver directory: /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run
Tue May 20 09:28:48 PDT 2025
Running parallel timing tests...
* Running prediction-scalability test in scalability_test.
** Running prediction-scalability_np1 on 1 ranks.
++ runoptions='-n 1'
++ [[ ! -z '' ]]
++ jsrun -g 1 -a 1 -n 1 bash /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/emirge/mirgecom/scripts/lassen-parallel-spawner.sh python -u -O -m mpi4py driver.py -c prediction-scalability_np1 -g /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/scalability_test/log_data -i run_params_np1.yaml --log --lazy
Custom casename 'prediction-scalability_np1'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
++ return_code=1
++ set +x
mv: cannot stat ‘viz_data’: No such file or directory
mv: cannot stat ‘restart_data’: No such file or directory
**  scalability_test/prediction-scalability_np1 failed.
** Running prediction-scalability_np2 on 2 ranks.
++ runoptions='-n 2'
++ [[ ! -z '' ]]
++ jsrun -g 1 -a 1 -n 2 bash /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/emirge/mirgecom/scripts/lassen-parallel-spawner.sh python -u -O -m mpi4py driver.py -c prediction-scalability_np2 -g /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/scalability_test/log_data -i run_params_np2.yaml --log --lazy
Custom casename 'prediction-scalability_np2'
Custom casename 'prediction-scalability_np2'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
++ return_code=1
++ set +x
mv: cannot stat ‘viz_data’: No such file or directory
mv: cannot stat ‘restart_data’: No such file or directory
**  scalability_test/prediction-scalability_np2 failed.
** Running prediction-scalability_np4 on 4 ranks.
++ runoptions='-n 4'
++ [[ ! -z '' ]]
++ jsrun -g 1 -a 1 -n 4 bash /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/emirge/mirgecom/scripts/lassen-parallel-spawner.sh python -u -O -m mpi4py driver.py -c prediction-scalability_np4 -g /p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/scalability_test/log_data -i run_params_np4.yaml --log --lazy
Custom casename 'prediction-scalability_np4'
Custom casename 'prediction-scalability_np4'
Custom casename 'prediction-scalability_np4'
Custom casename 'prediction-scalability_np4'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 214, in main
    run_command_line(args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/miniforge3/envs/timing.pilot/lib/python3.12/site-packages/mpi4py/run.py", line 46, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "driver.py", line 51, in <module>
    from mirgecom.simutil import ApplicationOptionsError
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/mirgecom/mirgecom/simutil.py", line 87, in <module>
    import grudge.op as op
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/op.py", line 132, in <module>
    from grudge.trace_pair import (
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 514, in <module>
    class _TagKeyBuilder(KeyBuilder):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/emirge/grudge/grudge/trace_pair.py", line 515, in _TagKeyBuilder
    def update_for_type(self, key_hash: Hash, key: type) -> None:
                                        ^^^^
NameError: name 'Hash' is not defined. Did you mean: 'hash'?
++ return_code=1
++ set +x
mv: cannot stat ‘viz_data’: No such file or directory
mv: cannot stat ‘restart_data’: No such file or directory
**  scalability_test/prediction-scalability_np4 failed.
Tue May 20 09:29:07 PDT 2025
Scaling/timing tests done.
Passing tests: 
Failing tests:  scalability_test/prediction-scalability_np1 scalability_test/prediction-scalability_np2 scalability_test/prediction-scalability_np4

------------------------------------------------------------
Sender: LSF System <lsfadmin@lassen710>
Subject: Job 7264499: <scale4> in cluster <lassen> Exited

Job <scale4> was submitted from host <lassen709> by user <mtcampbe> in cluster <lassen> at Tue May 20 09:22:44 2025
Job was executed on host(s) <1*lassen710>, in queue <pbatch>, as user <mtcampbe> in cluster <lassen> at Tue May 20 09:28:40 2025
                            <40*lassen500>
</g/g17/mtcampbe> was used as the home directory.
</p/gpfs1/mtcampbe/CEESD/AutomatedTesting/RepoMonitoring/pilot-timing/y3-prediction-scaling-run/scalability_test> was used as the working directory.
Started at Tue May 20 09:28:40 2025
Terminated at Tue May 20 09:29:39 2025
Results reported at Tue May 20 09:29:39 2025

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#!/bin/bash
#BSUB -nnodes 1
#BSUB -G uiuc
#BSUB -W 180
#BSUB -J scale4
#BSUB -q pbatch
#BSUB -o scal4.txt

source ../emirge/config/activate_env.sh
source ../emirge/mirgecom/scripts/mirge-testing-env.sh
source ../scripts/multi_scalability.sh -p ../ -n 4



------------------------------------------------------------

Exited with exit code 3.

Resource usage summary:

    CPU time :                                   0.28 sec.
    Max Memory :                                 59 MB
    Average Memory :                             54.71 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   1634 MB
    Max Processes :                              4
    Max Threads :                                27
    Run time :                                   59 sec.
    Turnaround time :                            415 sec.

The output (if any) is above this job summary.

